### ISSUE TITLE
prepare local RaspBerryPi-Development Environment

### ISSUE THREAD

**Issue by tim-pl-m** [tim-pl-m/CIR-AutoDJ#5]
Abnahmekritieren:
-Auf dem Laptop wird ein RaspberryPi simuliert
-Alles nötige im Git eingecheckt und in der Readme dokumentiert
-Review durch jemand anderes

Zeit: 4h

**Comment by floooko** [comment]
http://debian.uvigo.es/debian-cd/9.2.1/multi-arch/iso-cd/

**Comment by tim-pl-m** [comment]
http://debian.uvigo.es/debian-cd/8.7.1-live/i386/iso-hybrid/debian-live-8.7.1-i386-standard.iso

**Comment by floooko** [comment]
https://virtualboxes.org/doc/installing-guest-additions-on-debian/

**Comment by tim-pl-m** [comment]
apt-get install build-essential module-assistant
m-a prepare
